/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['blockquote[_ngcontent-%COMP%]{border-left:5px #158126 solid;background:#fff;padding:20px 20px 20px 40px}blockquote[_ngcontent-%COMP%]::before{left:1em}/*# sourceMappingURL=home.component.css.map */'];