/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['blockquote[_ngcontent-%COMP%] {\n  border-left:5px #158126 solid;\n  background:#fff;\n  padding:20px 20px 20px 40px;\n}\nblockquote[_ngcontent-%COMP%]::before {\n  left: 1em;\n}'];